# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57391b265a42736bc54156969c35c4236d87217d03c5c504498b81160bf201b0b09e2ad89468a3c455086e0159b26010240214d9b343e37ed5f51290277b6175

test:
  secret_key_base: 6ef05eaff61913baa4b6bdfd5cade557c9034acc63643a2ca63430be0913ed822ac972ff22d3bdcbbe7f5cf2beb15d138712e1f7170b8041ab5842522b2ff8f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


